new branch from main
noya-app/noya pull request #18
Opened 2021-04-08 00:33 UTC by milg15

okey new name but same branch 👍

2021-04-10 15:21 UTC, dabbott requested changes

2021-04-10 15:21 UTC, dabbott commented on packages/app/src/containers/SwatchesToolbar.tsx
> +            onClick={() => {
We should add a `useCallback` here. This is the function that would need `useCallback` most, since without it, the `Button` will always re-render

2021-04-13 03:01 UTC, milg15 commented
Okey I had to do some sync, it was working weird 😆 I hope it keeps working correctly.

2021-04-13 03:20 UTC, dabbott commented
After I merged your other branch, it looks like there are a few conflicts. Can you try resolving those?

2021-04-13 06:22 UTC, milg15 commented
#20 Third time's a Charm

2021-04-13 06:22 UTC, closed without merging