Line caps and joins #291
noya-app/noya pull request #293
Opened 2021-12-04 02:47 UTC by milg15

2021-12-05 23:53 UTC, dabbott commented
I pushed an update that gets the canvas rendering working. The main thing was propagating the border options into `getStrokedPath`, rather than setting them on the Paint. We actually convert every stroke into a new path and then "fill" it, since that lets us do things like gradient strokes.

2021-12-06 00:15 UTC, dabbott requested changes
Looks great! A commented on a couple small things. 

FYI I also remembered I removed the `borderOptions.isEnabled` check in my previous change. I don't think there's actually a way to disable border options in Sketch, and I don't think we'll have one either

2021-12-06 00:15 UTC, dabbott commented on packages/app/src/containers/BorderInspector.tsx
> +  const BorderInspectorExpanded = useMemo(() => {
Lowercase `borderInspectorExpanded` cause it's not a component

2021-12-06 00:15 UTC, dabbott commented on packages/app/src/components/inspector/ArrayController.tsx
> +  expandedContent?: ReactNode;
For consistency with `renderItem` let's make this a "render prop" . I.e. `renderExpandedContent?: () => ReactNode`.

This also has the small perf benefit of not needing to run unless it's actually expanded and visible.

2021-12-07 02:30 UTC, milg15 commented
Hopefully, this makes sense

2021-12-09 19:32 UTC, dabbott commented
We were still using `expandedContent` on the CheckboxArrayController, so I swapped it for `renderExpandedContent`

2021-12-09 19:32 UTC, dabbott approved these changes

2021-12-10 00:23 UTC, merged